name: http-adapter
on:
  push:
    branches:
      - "*"
    tags_ignore:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features --tests -- -D warnings
        env:
          RUSTFLAGS: '--cfg reqwest_unstable'

      - name: Test
        run: cargo test --workspace --all-targets --all-features
        env:
          RUSTFLAGS: '--cfg reqwest_unstable'
